systems:
  basedir: "./logs"

model:
  model_name: "HexPlane"
  N_voxel_init: 32768 # Paper: 32^3

  # We heuristically set initial time_grid and final time grid. 
  # A common strategy to set these two parameters for DNeRF dataset is:
  # We empirically set time_grid_final = int(0.24 * N_frames), and time_grid_init = int(0.5 * time_grid_final)
  # We show N_frames for each video 
  # "standup": 150; "jumpingjacks": 200; "hook"   : 100; "bouncingballs": 150
  # "lego"   :  50; "hellwarrior" : 100; "mutant" : 150; "trex"         : 200
  time_grid_init: 6  
  time_grid_final: 12
  upsampling_type: unaligned
  upsample_list: [4000, 8000]
  update_emptymask_list: [5000, 10000] # Paper: 4k, 10k
  nSamples: 1000000


data:
  datadir: "./data/lego"
  scene_bbox_min: [-1.5, -1.5, -1.5]
  scene_bbox_max: [1.5, 1.5, 1.5]
  downsample: 2.5 # assert (img_res / ds) % 16 (macro_block_size) = 0

optim:
  n_iters: 25000

render_test: True
render_path: True
expname: dnerf_slim_lego
